# Generated by Django 5.2.13 on 2026-04-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("B", "Básico"),
                            ("I", "Intermediário"),
                            ("A", "Avançado"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=30)),
                ("cpf", models.CharField(max_length=11)),
                ("data_nascimento", models.DateField()),
                ("celular", models.CharField(max_length=14)),
            ],
        ),
    ]
