# Generated by Django 5.2.13 on 2026-04-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cursos",
            new_name="Curso",
        ),
        migrations.RenameModel(
            old_name="Estudantes",
            new_name="Estudante",
        ),
    ]
